[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-openSUSE_BreezeDark-r4
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-openSUSE_BreezeDark-r4
GtkTheme=oomox-openSUSE_BreezeDark-r4
IconTheme=oomox-openSUSE_BreezeDark-r4
MetacityTheme=oomox-openSUSE_BreezeDark-r4
